name: check-modules
on:
  push:

jobs:
  build-with-modules:
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang6]
    runs-on: ubuntu-18.04
    name: ${{ matrix.compiler }}-check-modules
    env:
      COMPILER: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
      - name: Checkout modules
        run: ./apps/ci/ci-install-modules.sh
      - name: Cache
        uses: actions/cache@v1.1.2
        with:
          path: /home/runner/.ccache
          key: ccache:${{ matrix.compiler }}:${{ github.workflow }}:${{ github.ref }}:${{ github.sha }}
          restore-keys: |
            ccache:${{ github.workflow }}:${{ matrix.compiler }}:${{ github.ref }}
            ccache:${{ matrix.compiler }}:${{ github.workflow }}:${{ github.ref }}
            ccache:${{ matrix.compiler }}:${{ github.workflow }}
            ccache:${{ matrix.compiler }}
            ccache
      - name: Configure OS
        run: source ./apps/ci/ci-install.sh
        env:
          CONTINUOUS_INTEGRATION: true
      - name: Import db
        run: source ./apps/ci/ci-import-db.sh
      - name: Build
        run: source ./apps/ci/ci-compile.sh
      - name: Dry run
        run: source ./apps/ci/ci-worldserver-dry-run.sh
      - name: Check startup errors
        run: source ./apps/ci/ci-error-check.sh
